<script setup lang="ts">
import { computed, ref } from 'vue'
import AppModal from '../../components/conservation/AppModal.vue'
import { conservationStore, plantFor, speciesForPlant, type Observation } from '../../data/conservation'
const search=ref(''),status=ref(''),species=ref(''),location=ref(''),botanist=ref(''),date=ref(''),selected=ref<Observation|null>(null),plantModal=ref(false),historyModal=ref(false)
const filtered=computed(()=>conservationStore.observations.filter(o=>{const sp=speciesForPlant(o.plantId);return `${o.id} ${o.plantId} ${sp?.scientificName} ${o.recordedBy}`.toLowerCase().includes(search.value.toLowerCase())&&(!status.value||o.status===status.value)&&(!species.value||sp?.id===species.value)&&(!location.value||o.location===location.value)&&(!botanist.value||o.recordedBy===botanist.value)&&(!date.value||o.observedAt.startsWith(new Date(date.value+'T00:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}))) }))
const history=computed(()=>selected.value?conservationStore.observations.filter(o=>o.plantId===selected.value?.plantId):[])
function open(o:Observation){selected.value=o;plantModal.value=false;historyModal.value=false}
</script>
<template><section class="page-intro"><div><p class="page-kicker">FIELD RECORDS</p><h2>Observations</h2><p>Browse time-specific measurements submitted by botanists without overwriting plant history.</p></div></section><div class="control-bar"><label class="field search-field"><span>Search</span><input v-model="search" placeholder="Observation ID, Plant ID, species or botanist" /></label><label class="field"><span>Status</span><select v-model="status"><option value="">All statuses</option><option v-for="s in ['Draft','Pending Review','Approved','Rejected','Correction Required','Flagged']" :key="s">{{s}}</option></select></label><label class="field"><span>Species</span><select v-model="species"><option value="">All species</option><option v-for="s in conservationStore.species" :key="s.id" :value="s.id">{{s.commonName}}</option></select></label><label class="field"><span>Location</span><select v-model="location"><option value="">All locations</option><option v-for="l in [...new Set(conservationStore.observations.map(o=>o.location))]" :key="l">{{l}}</option></select></label><label class="field"><span>Botanist</span><select v-model="botanist"><option value="">All botanists</option><option v-for="b in [...new Set(conservationStore.observations.map(o=>o.recordedBy))]" :key="b">{{b}}</option></select></label><label class="field"><span>Date</span><input v-model="date" type="date" /></label></div>
<section class="panel"><div class="table-scroll"><table><thead><tr><th>Observation ID</th><th>Plant ID</th><th>Species</th><th>Recorded By</th><th>Height</th><th>Growth Stage</th><th>Health</th><th>Location</th><th>Observation Date</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="o in filtered" :key="o.id"><td><strong>{{o.id}}</strong></td><td>{{o.plantId}}</td><td><em>{{speciesForPlant(o.plantId)?.scientificName}}</em></td><td>{{o.recordedBy}}</td><td>{{o.height}}</td><td>{{o.growthStage}}</td><td>{{o.health}}</td><td>{{o.location}}</td><td>{{o.observedAt}}</td><td><span class="badge" :class="o.status.toLowerCase().replaceAll(' ','-')">{{o.status}}</span></td><td><div class="action-group"><button class="action-button" @click="open(o)">View</button><button class="action-button" @click="selected=o;plantModal=true">View Plant</button><button class="action-button" @click="selected=o;historyModal=true">History</button><RouterLink class="action-button" :to="{name:'conservation-map',query:{plant:o.plantId}}">Location</RouterLink><RouterLink v-if="o.status==='Pending Review'" class="action-button" :to="{name:'conservation-reviews',query:{review:o.id}}">Review</RouterLink></div></td></tr></tbody></table></div></section>
<AppModal v-if="selected&&!plantModal&&!historyModal" :title="`Observation ${selected.id}`" :subtitle="`${selected.plantId} · ${speciesForPlant(selected.plantId)?.scientificName}`" wide @close="selected=null"><dl class="detail-list"><div><dt>Recorded By</dt><dd>{{selected.recordedBy}}</dd></div><div><dt>Date / Time</dt><dd>{{selected.observedAt}}</dd></div><div><dt>Height</dt><dd>{{selected.height}}</dd></div><div><dt>Growth Stage</dt><dd>{{selected.growthStage}}</dd></div><div><dt>Health Status</dt><dd>{{selected.health}}</dd></div><div><dt>Morphology</dt><dd>{{selected.morphology}}</dd></div><div><dt>Other Notes</dt><dd>{{selected.notes}}</dd></div><div><dt>GPS Accuracy</dt><dd>{{selected.gpsAccuracy}}</dd></div><div><dt>Coordinates</dt><dd>{{plantFor(selected.plantId)?.latitude}}, {{plantFor(selected.plantId)?.longitude}}</dd></div><div><dt>Review</dt><dd>{{selected.status}} · {{selected.reviewedBy||'Not reviewed'}}</dd></div><div><dt>Reviewed At</dt><dd>{{selected.reviewedAt||'—'}}</dd></div><div><dt>Review Comments</dt><dd>{{selected.reviewComment||'—'}}</dd></div></dl><h3>Media</h3><div class="media-grid"><div v-for="p in selected.photos" :key="p" class="media-placeholder">{{p}} photo</div></div></AppModal>
<AppModal v-if="selected&&plantModal" :title="`Plant ${selected.plantId}`" :subtitle="speciesForPlant(selected.plantId)?.scientificName" @close="plantModal=false;selected=null"><dl class="detail-list"><div><dt>Registered By</dt><dd>{{plantFor(selected.plantId)?.registeredBy}}</dd></div><div><dt>Registered At</dt><dd>{{plantFor(selected.plantId)?.registeredAt}}</dd></div><div><dt>Zone</dt><dd>{{plantFor(selected.plantId)?.zone}}</dd></div><div><dt>Health</dt><dd>{{plantFor(selected.plantId)?.health}}</dd></div></dl></AppModal>
<AppModal v-if="selected&&historyModal" :title="`${selected.plantId} Observation History`" subtitle="Historical measurements remain separate records." wide @close="historyModal=false;selected=null"><div class="table-scroll"><table><thead><tr><th>ID</th><th>Date</th><th>Height</th><th>Health</th><th>Status</th></tr></thead><tbody><tr v-for="o in history" :key="o.id"><td>{{o.id}}</td><td>{{o.observedAt}}</td><td>{{o.height}}</td><td>{{o.health}}</td><td><span class="badge" :class="o.status.toLowerCase().replaceAll(' ','-')">{{o.status}}</span></td></tr></tbody></table></div></AppModal></template>
<style scoped>a.action-button{text-decoration:none}</style>
