<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppModal from '../../components/conservation/AppModal.vue'
import { conservationStore, type ConservationStatus, type SpeciesRecord } from '../../data/conservation'
const route=useRoute(),router=useRouter(), search=ref(''),family=ref(''),status=ref(''),modal=ref<'form'|'view'|'delete'|null>(null),selected=ref<SpeciesRecord|null>(null),editing=ref(false)
const blank=()=>({id:`SP${String(conservationStore.species.length+1).padStart(3,'0')}`,scientificName:'',commonName:'',genus:'',family:'',status:'Least Concern' as ConservationStatus,plantCount:0,updated:'3 Oct 2026',description:'',habitat:'',distribution:'',cultural:'',image:'',supporting:''})
const form=reactive<SpeciesRecord>(blank())
const families=computed(()=>[...new Set(conservationStore.species.map(s=>s.family))])
const filtered=computed(()=>conservationStore.species.filter(s=>`${s.scientificName} ${s.commonName} ${s.family}`.toLowerCase().includes(search.value.toLowerCase())&&(!family.value||s.family===family.value)&&(!status.value||s.status===status.value)))
function openForm(item?:SpeciesRecord){editing.value=!!item;Object.assign(form,item?{...item}:blank());modal.value='form'}
function save(){if(!form.scientificName||!form.commonName||!form.genus||!form.family)return;if(editing.value){const i=conservationStore.species.findIndex(s=>s.id===form.id);conservationStore.species[i]={...form}}else conservationStore.species.push({...form});modal.value=null;router.replace({query:{}})}
function view(s:SpeciesRecord){selected.value=s;modal.value='view'}function confirmDelete(s:SpeciesRecord){selected.value=s;modal.value='delete'}function remove(){if(selected.value)conservationStore.species.splice(conservationStore.species.findIndex(s=>s.id===selected.value?.id),1);modal.value=null}
onMounted(()=>{if(route.query.action==='add')openForm()})
</script>
<template><section class="page-intro"><div><p class="page-kicker">KNOWLEDGE BASE</p><h2>Plant Species</h2><p>Manage official taxonomic, ecological and conservation information.</p></div></section>
<div class="control-bar"><label class="field search-field"><span>Search species</span><input v-model="search" placeholder="Scientific name, common name or family" /></label><label class="field"><span>Family</span><select v-model="family"><option value="">All families</option><option v-for="f in families" :key="f">{{f}}</option></select></label><label class="field"><span>Conservation status</span><select v-model="status"><option value="">All statuses</option><option v-for="s in ['Least Concern','Near Threatened','Vulnerable','Endangered','Critically Endangered']" :key="s">{{s}}</option></select></label><button class="primary-button" @click="openForm()">+ Add Species</button></div>
<section class="panel"><div class="table-scroll"><table><thead><tr><th>Species ID</th><th>Scientific Name</th><th>Common Name</th><th>Genus</th><th>Family</th><th>Conservation Status</th><th>Plant Records</th><th>Last Updated</th><th>Actions</th></tr></thead><tbody><tr v-for="s in filtered" :key="s.id"><td><strong>{{s.id}}</strong></td><td><em>{{s.scientificName}}</em></td><td>{{s.commonName}}</td><td>{{s.genus}}</td><td>{{s.family}}</td><td><span class="badge" :class="s.status.toLowerCase().replaceAll(' ','-')">{{s.status}}</span></td><td>{{s.plantCount}}</td><td>{{s.updated}}</td><td><div class="action-group"><button class="action-button" @click="view(s)">View</button><button class="action-button" @click="openForm(s)">Edit</button><button class="action-button danger" @click="confirmDelete(s)">Delete</button></div></td></tr><tr v-if="!filtered.length"><td colspan="9" class="empty-row">No species match the selected filters.</td></tr></tbody></table></div></section>
<AppModal v-if="modal==='form'" :title="editing?'Edit Species':'Add Species'" subtitle="Species records contain general biological information, not individual observations." wide @close="modal=null"><form class="form-grid" @submit.prevent="save"><label class="form-field"><span>Species ID</span><input v-model="form.id" readonly /></label><label class="form-field"><span>Scientific Name</span><input v-model="form.scientificName" required /></label><label class="form-field"><span>Common Name</span><input v-model="form.commonName" required /></label><label class="form-field"><span>Genus</span><input v-model="form.genus" required /></label><label class="form-field"><span>Family</span><input v-model="form.family" required /></label><label class="form-field"><span>Conservation Status</span><select v-model="form.status"><option v-for="s in ['Least Concern','Near Threatened','Vulnerable','Endangered','Critically Endangered']" :key="s">{{s}}</option></select></label><label class="form-field full"><span>Description</span><textarea v-model="form.description"></textarea></label><label class="form-field full"><span>Habitat / Ecological Information</span><textarea v-model="form.habitat"></textarea></label><label class="form-field full"><span>Distribution Information</span><textarea v-model="form.distribution"></textarea></label><label class="form-field full"><span>Cultural Significance</span><textarea v-model="form.cultural"></textarea></label><label class="form-field"><span>Representative Photograph / Image URL</span><input v-model="form.image" /></label><label class="form-field"><span>Supporting Information</span><input v-model="form.supporting" /></label><div class="modal-actions form-field full"><button type="button" class="secondary-button" @click="modal=null">Cancel</button><button class="primary-button">{{editing?'Save Changes':'Create Species'}}</button></div></form></AppModal>
<AppModal v-if="modal==='view'&&selected" :title="selected.scientificName" :subtitle="selected.commonName" @close="modal=null"><dl class="detail-list"><div><dt>Species ID</dt><dd>{{selected.id}}</dd></div><div><dt>Family</dt><dd>{{selected.family}}</dd></div><div><dt>Conservation Status</dt><dd>{{selected.status}}</dd></div><div><dt>Plant Records</dt><dd>{{selected.plantCount}}</dd></div><div><dt>Habitat</dt><dd>{{selected.habitat}}</dd></div><div><dt>Distribution</dt><dd>{{selected.distribution}}</dd></div></dl><p>{{selected.description}}</p></AppModal>
<AppModal v-if="modal==='delete'&&selected" title="Delete species record?" :subtitle="`${selected.id} — ${selected.scientificName}`" @close="modal=null"><p>This removes the species from this frontend mock state. This action cannot be undone during the current session.</p><div class="modal-actions"><button class="secondary-button" @click="modal=null">Cancel</button><button class="danger-button" @click="remove">Delete Species</button></div></AppModal></template>
