<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppModal from '../../components/conservation/AppModal.vue'
import { conservationStore, plantFor, speciesForPlant, type Observation, type ObservationStatus } from '../../data/conservation'
const route=useRoute(),router=useRouter(),search=ref(''),status=ref(''),species=ref(''),date=ref(''),selected=ref<Observation|null>(null),comment=ref(''),error=ref('')
const counts=computed(()=>[['Pending Review',conservationStore.observations.filter(o=>o.status==='Pending Review').length],['Correction Required',conservationStore.observations.filter(o=>o.status==='Correction Required').length],['Flagged',conservationStore.observations.filter(o=>o.status==='Flagged').length],['Approved Today',conservationStore.observations.filter(o=>o.status==='Approved'&&o.reviewedAt?.startsWith('3 Oct')).length]])
const filtered=computed(()=>conservationStore.observations.filter(o=>`${o.id} ${o.plantId} ${speciesForPlant(o.plantId)?.scientificName} ${o.recordedBy}`.toLowerCase().includes(search.value.toLowerCase())&&(!status.value||o.status===status.value)&&(!species.value||speciesForPlant(o.plantId)?.id===species.value)&&(!date.value||o.submittedAt.includes(new Date(date.value+'T00:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})))))
function open(o:Observation){selected.value=o;comment.value=o.reviewComment||'';error.value=''}
function decide(next:ObservationStatus){if(!selected.value)return;if(next!=='Approved'&&!comment.value.trim()){error.value='An officer comment is required for this decision.';return}selected.value.status=next;selected.value.reviewComment=comment.value||'Submission verified.';selected.value.reviewedBy='Officer01';selected.value.reviewedAt='3 Oct 2026';selected.value=null;router.replace({query:{}})}
onMounted(()=>{const id=String(route.query.review||'');const o=conservationStore.observations.find(x=>x.id===id);if(o)open(o)})
</script>
<template><section class="page-intro"><div><p class="page-kicker">VERIFICATION WORKFLOW</p><h2>Review Submissions</h2><p>Verify botanist observations and preserve a clear review decision.</p></div></section><section class="summary-grid"><article v-for="c in counts" :key="String(c[0])" class="summary-card"><p>{{c[0]}}</p><strong>{{c[1]}}</strong><small>Observation submissions</small></article></section><div class="control-bar"><label class="field search-field"><span>Search</span><input v-model="search" placeholder="Observation ID, Plant ID, species or botanist" /></label><label class="field"><span>Review status</span><select v-model="status"><option value="">All statuses</option><option v-for="s in ['Pending Review','Approved','Rejected','Correction Required','Flagged']" :key="s">{{s}}</option></select></label><label class="field"><span>Species</span><select v-model="species"><option value="">All species</option><option v-for="s in conservationStore.species" :key="s.id" :value="s.id">{{s.commonName}}</option></select></label><label class="field"><span>Date</span><input v-model="date" type="date" /></label></div>
<section class="panel"><div class="table-scroll"><table><thead><tr><th>Observation ID</th><th>Plant ID</th><th>Species</th><th>Submitted By</th><th>Location</th><th>Submitted Date</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="o in filtered" :key="o.id"><td><strong>{{o.id}}</strong></td><td>{{o.plantId}}</td><td><em>{{speciesForPlant(o.plantId)?.scientificName}}</em></td><td>{{o.recordedBy}}</td><td>{{o.location}}</td><td>{{o.submittedAt}}</td><td><span class="badge" :class="o.status.toLowerCase().replaceAll(' ','-')">{{o.status}}</span></td><td><button class="action-button" @click="open(o)">Review</button></td></tr></tbody></table></div></section>
<AppModal v-if="selected" :title="`Review ${selected.id}`" :subtitle="`${selected.plantId} · submitted by ${selected.recordedBy}`" wide @close="selected=null"><div class="two-column"><div><dl class="detail-list"><div><dt>Species</dt><dd>{{speciesForPlant(selected.plantId)?.scientificName}}</dd></div><div><dt>Taxonomy</dt><dd>{{speciesForPlant(selected.plantId)?.family}}</dd></div><div><dt>Height</dt><dd>{{selected.height}}</dd></div><div><dt>Growth Stage</dt><dd>{{selected.growthStage}}</dd></div><div><dt>Health</dt><dd>{{selected.health}}</dd></div><div><dt>Morphology</dt><dd>{{selected.morphology}}</dd></div><div><dt>Coordinates</dt><dd>{{plantFor(selected.plantId)?.latitude}}, {{plantFor(selected.plantId)?.longitude}} ({{selected.gpsAccuracy}})</dd></div><div><dt>Submission Date</dt><dd>{{selected.submittedAt}}</dd></div></dl><h3>Photographs</h3><div class="media-grid"><div v-for="p in selected.photos" :key="p" class="media-placeholder">{{p}}</div></div></div><aside><h3>Observation History</h3><div v-for="o in conservationStore.observations.filter(x=>x.plantId===selected?.plantId)" :key="o.id" class="history-item"><strong>{{o.id}}</strong><span>{{o.observedAt}} · {{o.height}} · {{o.health}}</span></div><label class="form-field officer-comment"><span>Officer Comment</span><textarea v-model="comment" placeholder="Record the reason or required action"></textarea></label><p v-if="error" class="form-error">{{error}}</p></aside></div><div class="modal-actions"><button class="primary-button" @click="decide('Approved')">Approve</button><button class="danger-button" @click="decide('Rejected')">Reject</button><button class="secondary-button" @click="decide('Correction Required')">Request Correction</button><button class="secondary-button" @click="decide('Flagged')">Flag</button></div></AppModal></template>
<style scoped>.history-item{padding:10px 0;display:grid;gap:3px;border-bottom:1px solid #edf0ed;font-size:10px}.history-item span{color:#829088}.officer-comment{margin-top:18px}.form-error{color:#b84d42;font-size:10px}</style>
